export const FAILED_LOGIN_USER = 'FAILED_LOGIN_USER';
export const SUCCESS_LOGIN_USER = 'SUCCESS_LOGIN_USER';
export const FAILED_SIGNUP_USER = 'FAILED_SIGNUP_USER';
export const SUCCESS_SIGNUP_USER = 'SUCCESS_SIGNUP_USER';
export const MODEL_INFO = 'MODEL_INFO';
export const LOGOUT_USER = 'LOGOUT_USER'